### ISSUE TITLE
Suggestion: Make "real" https://openipc.org/ page

### ISSUE THREAD

**Issue by pfalcon** [OpenIPC/openipc.github.io#5]
Currently, if you visit https://openipc.org/ , you get redirected to https://openipc.org/about/ . That may be minor, but that's not how most of web sites work. When you visit https://openipc.org/ , you stay at that URL, and the corresponding page is called "index", not "about".

Fixing that minor thing may be a good first step towards making a page which would explain "umbrella" structure of the project. (As was discussed on the Telegram.)

**Comment by ZigFisher** [comment]
Of course, how will someone find the strength to create a page index.html with the description of the umbrella structure, we will switch the root of the site to it.

**Comment by pfalcon** [comment]
I think it makes sense to start from simple cleanups like this. YMMV

> create a page index.html with the description of the umbrella structure

Discussion of that is started in https://github.com/OpenIPC/openipc.github.io/issues/7. Note that in the end, only *maintainers* of the project may know what it is/its goals, and can formulate them properly. Of course, others may ask questions to them and try to write something based on their answers. Again, that's what #7 tries to achieve.

**Comment by ZigFisher** [comment]
> Currently, if you visit https://openipc.org/ , you get redirected to https://openipc.org/about/ . That may be minor, but that's not how most of web sites work. When you visit https://openipc.org/ , you stay at that URL, and the corresponding page is called "index", not "about".
> 
> Fixing that minor thing may be a good first step towards making a page which would explain "umbrella" structure of the project. (As was discussed on the Telegram.)


Now fixed, thanks
